# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BJJfCFVQQnt1ojiTTnpXAqC_lP0KulUn
"""

pip install streamlit

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import streamlit as st

# -----------------------------------------------------------------------------
# Path setup so Streamlit can import from src/
# -----------------------------------------------------------------------------
CURRENT_FILE = Path("src/inference.py").resolve()
PROJECT_ROOT = CURRENT_FILE.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from src.inference import (
    describe_prediction,
    get_required_feature_columns,
    predict_from_dict,
)

# -----------------------------------------------------------------------------
# Page configuration
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="Aero Toolkit",
    page_icon="🛩️",
    layout="wide",
)

# -----------------------------------------------------------------------------
# Small plotting helper for the V1 app
# -----------------------------------------------------------------------------
def plot_airfoil_and_separation(
    root_chord: float,
    tip_chord: float,
    sweep_angle: float,
    separation_x_over_c: float,
    airfoil_family: str,
) -> plt.Figure:
    """
    Create a simple 2D conceptual wing-section style plot and mark the predicted
    separation location along the normalized chord.

    This is intentionally lightweight for Version 1. It is not a CFD visualization.
    """
    fig, ax = plt.subplots(figsize=(8, 3))

    # Draw a simple normalized chord line
    ax.plot([0, 1], [0, 0], linewidth=3)

    # Mark the separation location
    ax.scatter([separation_x_over_c], [0], s=100)
    ax.axvline(separation_x_over_c, linestyle="--", linewidth=1)

    # Cosmetic labels
    ax.text(
        separation_x_over_c,
        0.08,
        f"x/c = {separation_x_over_c:.3f}",
        ha="center",
        va="bottom",
    )

    ax.set_xlim(0, 1)
    ax.set_ylim(-0.25, 0.35)
    ax.set_xlabel("Normalized chord location (x/c)")
    ax.set_yticks([])
    ax.set_title(
        f"Predicted Flow Separation Location | {airfoil_family.title()} | "
        f"Root chord={root_chord:.2f}, Tip chord={tip_chord:.2f}, Sweep={sweep_angle:.1f}°"
    )
    ax.grid(True, axis="x", alpha=0.3)

    return fig


# -----------------------------------------------------------------------------
# App title and overview
# -----------------------------------------------------------------------------
st.title("Aerodynamic Screening Toolkit")
st.write(
    "This Version 1 app uses a saved machine learning pipeline to predict the flow "
    "separation location `separation_x_over_c` from aerodynamic and geometry inputs."
)

with st.expander("Current Version 1 scope"):
    st.markdown(
        """
        **What this app does**
        - accepts parameterized wing and flow inputs
        - predicts `separation_x_over_c`
        - provides a simple risk interpretation
        - shows a lightweight conceptual plot

        **What this app does not do**
        - full CFD simulation
        - raw 3D CAD upload
        - full-aircraft modeling
        - production-grade aerodynamic visualization
        """
    )

# -----------------------------------------------------------------------------
# Sidebar inputs
# -----------------------------------------------------------------------------
st.sidebar.header("Input Parameters")

airfoil_family = st.sidebar.selectbox(
    "Airfoil Family",
    ["symmetric", "cambered", "biomimetic"],
    index=2,
)

if airfoil_family == "biomimetic":
    tubercle_shape_options = ["whale", "biomimetic_v1"]
    default_tubercle_shape_index = 0
    tubercle_disabled = False
    default_amplitude = 26.247
    default_wavelength = 49.607
else:
    tubercle_shape_options = ["none"]
    default_tubercle_shape_index = 0
    tubercle_disabled = True
    default_amplitude = 0.0
    default_wavelength = 0.0

tubercle_shape = st.sidebar.selectbox(
    "Tubercle Shape",
    tubercle_shape_options,
    index=default_tubercle_shape_index,
)

tubercle_amplitude = st.sidebar.number_input(
    "Tubercle Amplitude",
    min_value=0.0,
    max_value=100.0,
    value=float(default_amplitude),
    step=0.1,
    disabled=tubercle_disabled,
)

tubercle_wavelength = st.sidebar.number_input(
    "Tubercle Wavelength",
    min_value=0.0,
    max_value=200.0,
    value=float(default_wavelength),
    step=0.1,
    disabled=tubercle_disabled,
)

root_chord = st.sidebar.number_input(
    "Root Chord",
    min_value=0.1,
    max_value=10.0,
    value=1.0,
    step=0.1,
)

tip_chord = st.sidebar.number_input(
    "Tip Chord",
    min_value=0.1,
    max_value=10.0,
    value=1.0,
    step=0.1,
)

sweep_angle = st.sidebar.number_input(
    "Sweep Angle (degrees)",
    min_value=0.0,
    max_value=80.0,
    value=0.0,
    step=1.0,
)

angle_of_attack = st.sidebar.number_input(
    "Angle of Attack (degrees)",
    min_value=-10.0,
    max_value=30.0,
    value=10.0,
    step=1.0,
)

airspeed = st.sidebar.number_input(
    "Airspeed",
    min_value=0.1,
    max_value=300.0,
    value=30.0,
    step=1.0,
)

# -----------------------------------------------------------------------------
# Build input dict exactly as the model expects
# -----------------------------------------------------------------------------
input_dict = {
    "airfoil_family": airfoil_family,
    "tubercle_amplitude": tubercle_amplitude,
    "tubercle_wavelength": tubercle_wavelength,
    "tubercle_shape": tubercle_shape,
    "root_chord": root_chord,
    "tip_chord": tip_chord,
    "sweep_angle": sweep_angle,
    "angle_of_attack": angle_of_attack,
    "airspeed": airspeed,
}

# -----------------------------------------------------------------------------
# Display current input schema for debugging / clarity
# -----------------------------------------------------------------------------
with st.expander("Show current input dictionary"):
    st.json(input_dict)
    st.write("Expected model feature order:")
    st.write(get_required_feature_columns())

# -----------------------------------------------------------------------------
# Prediction block
# -----------------------------------------------------------------------------
st.subheader("Model Output")

if st.button("Run Prediction", type="primary"):
    try:
        prediction = predict_from_dict(input_dict)
        label = describe_prediction(prediction)

        metric_col1, metric_col2 = st.columns(2)
        metric_col1.metric("Predicted separation_x_over_c", f"{prediction:.4f}")
        metric_col2.metric("Interpretation", label)

        fig = plot_airfoil_and_separation(
            root_chord=root_chord,
            tip_chord=tip_chord,
            sweep_angle=sweep_angle,
            separation_x_over_c=prediction,
            airfoil_family=airfoil_family,
        )
        st.pyplot(fig)

        output_df = pd.DataFrame([input_dict])
        output_df["predicted_separation_x_over_c"] = prediction
        st.write("Prediction record")
        st.dataframe(output_df, use_container_width=True)

    except Exception as e:
        st.error(f"Prediction failed: {e}")
        st.info(
            "Check that the saved .joblib model is present in the models/ folder, "
            "that the model filename matches what inference.py expects, and that "
            "the app inputs match the training feature schema exactly."
        )
else:
    st.info("Adjust the inputs in the sidebar, then click **Run Prediction**.")

# -----------------------------------------------------------------------------
# Footer note
# -----------------------------------------------------------------------------
st.caption(
    "Version 1 app note: this is a lightweight ML screening tool connected to a "
    "saved notebook-trained model artifact. It is not a full CFD solver."
)